[workspace]
resolver = "2"
members = [ "ryo",
    "ryo_ecs",
    "ryo_engine",
    "ryo_reflect",
    "ryo_reflect_derive",
    "ryo_wgpu", "ryo_window",
    "ryo_winit",
]

[profile.release]
codegen-units = 1
lto = true
