[package]
name = "ryo"
version = "0.1.0"
edition = "2021"

[dependencies]
ryo_engine = { path = "../ryo_engine" }
ryo_ecs = { path = "../ryo_ecs" }
ryo_window = { path = "../ryo_window" }
ryo_winit = { path = "../ryo_winit" }
ryo_wgpu = { path = "../ryo_wgpu" }
