[package]
name = "ryo_reflect"
version = "0.1.0"
edition = "2021"

[dependencies]
ryo_reflect_derive = { path = "../ryo_reflect_derive", optional = true }

[features]
rtti = []
derive = ["dep:ryo_reflect_derive"]
default = ["derive", "rtti"]
